language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.4.5
    - DJANGO=1.5.1
install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install git+https://github.com/cbmi/avocado.git@2.1
script:
    - python setup.py test
